// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// Kappas
NumericMatrix Kappas(IntegerVector y);
RcppExport SEXP _HZIP_Kappas(SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(Kappas(y));
    return rcpp_result_gen;
END_RCPP
}
// dLGG
double dLGG(double b, double mu, double sigma, double lambda, bool log);
RcppExport SEXP _HZIP_dLGG(SEXP bSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP lambdaSEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< bool >::type log(logSEXP);
    rcpp_result_gen = Rcpp::wrap(dLGG(b, mu, sigma, lambda, log));
    return rcpp_result_gen;
END_RCPP
}
// dPoisLGG
double dPoisLGG(NumericVector& theta2, NumericMatrix& wi, IntegerVector& yi, NumericVector& k, NumericVector& nodes, NumericVector& weights);
RcppExport SEXP _HZIP_dPoisLGG(SEXP theta2SEXP, SEXP wiSEXP, SEXP yiSEXP, SEXP kSEXP, SEXP nodesSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type theta2(theta2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type wi(wiSEXP);
    Rcpp::traits::input_parameter< IntegerVector& >::type yi(yiSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type k(kSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type nodes(nodesSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(dPoisLGG(theta2, wi, yi, k, nodes, weights));
    return rcpp_result_gen;
END_RCPP
}
// dPoisLGG_AGHQ
double dPoisLGG_AGHQ(NumericVector& theta2, NumericMatrix& wi, IntegerVector& yi, NumericVector& k, NumericVector& nodes, NumericVector& weights);
RcppExport SEXP _HZIP_dPoisLGG_AGHQ(SEXP theta2SEXP, SEXP wiSEXP, SEXP yiSEXP, SEXP kSEXP, SEXP nodesSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type theta2(theta2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type wi(wiSEXP);
    Rcpp::traits::input_parameter< IntegerVector& >::type yi(yiSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type k(kSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type nodes(nodesSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(dPoisLGG_AGHQ(theta2, wi, yi, k, nodes, weights));
    return rcpp_result_gen;
END_RCPP
}
// dBerLGG
double dBerLGG(NumericVector& theta1, NumericMatrix& xi, IntegerVector& yi, NumericVector& k);
RcppExport SEXP _HZIP_dBerLGG(SEXP theta1SEXP, SEXP xiSEXP, SEXP yiSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type theta1(theta1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< IntegerVector& >::type yi(yiSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(dBerLGG(theta1, xi, yi, k));
    return rcpp_result_gen;
END_RCPP
}
// dZIP
double dZIP(NumericVector& theta1, NumericVector& theta2, NumericMatrix& xi, NumericMatrix& wi, IntegerVector& yi, NumericVector& Qnodes, NumericVector& Qweights, bool log);
RcppExport SEXP _HZIP_dZIP(SEXP theta1SEXP, SEXP theta2SEXP, SEXP xiSEXP, SEXP wiSEXP, SEXP yiSEXP, SEXP QnodesSEXP, SEXP QweightsSEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type theta1(theta1SEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type theta2(theta2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type wi(wiSEXP);
    Rcpp::traits::input_parameter< IntegerVector& >::type yi(yiSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type Qnodes(QnodesSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type Qweights(QweightsSEXP);
    Rcpp::traits::input_parameter< bool >::type log(logSEXP);
    rcpp_result_gen = Rcpp::wrap(dZIP(theta1, theta2, xi, wi, yi, Qnodes, Qweights, log));
    return rcpp_result_gen;
END_RCPP
}
// lvero
double lvero(NumericVector theta, List xlist, List wlist, List ylist, NumericVector Qnodes, NumericVector Qweights);
RcppExport SEXP _HZIP_lvero(SEXP thetaSEXP, SEXP xlistSEXP, SEXP wlistSEXP, SEXP ylistSEXP, SEXP QnodesSEXP, SEXP QweightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< List >::type xlist(xlistSEXP);
    Rcpp::traits::input_parameter< List >::type wlist(wlistSEXP);
    Rcpp::traits::input_parameter< List >::type ylist(ylistSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Qnodes(QnodesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Qweights(QweightsSEXP);
    rcpp_result_gen = Rcpp::wrap(lvero(theta, xlist, wlist, ylist, Qnodes, Qweights));
    return rcpp_result_gen;
END_RCPP
}
// mlez_hat
double mlez_hat(NumericVector theta, List xlist, List wlist, List ylist);
RcppExport SEXP _HZIP_mlez_hat(SEXP thetaSEXP, SEXP xlistSEXP, SEXP wlistSEXP, SEXP ylistSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< List >::type xlist(xlistSEXP);
    Rcpp::traits::input_parameter< List >::type wlist(wlistSEXP);
    Rcpp::traits::input_parameter< List >::type ylist(ylistSEXP);
    rcpp_result_gen = Rcpp::wrap(mlez_hat(theta, xlist, wlist, ylist));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_HZIP_Kappas", (DL_FUNC) &_HZIP_Kappas, 1},
    {"_HZIP_dLGG", (DL_FUNC) &_HZIP_dLGG, 5},
    {"_HZIP_dPoisLGG", (DL_FUNC) &_HZIP_dPoisLGG, 6},
    {"_HZIP_dPoisLGG_AGHQ", (DL_FUNC) &_HZIP_dPoisLGG_AGHQ, 6},
    {"_HZIP_dBerLGG", (DL_FUNC) &_HZIP_dBerLGG, 4},
    {"_HZIP_dZIP", (DL_FUNC) &_HZIP_dZIP, 8},
    {"_HZIP_lvero", (DL_FUNC) &_HZIP_lvero, 6},
    {"_HZIP_mlez_hat", (DL_FUNC) &_HZIP_mlez_hat, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_HZIP(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
