# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Kappas <- function(y) {
    .Call(`_HZIP_Kappas`, y)
}

dLGG <- function(b, mu, sigma, lambda, log = FALSE) {
    .Call(`_HZIP_dLGG`, b, mu, sigma, lambda, log)
}

dPoisLGG <- function(theta2, wi, yi, k, nodes, weights) {
    .Call(`_HZIP_dPoisLGG`, theta2, wi, yi, k, nodes, weights)
}

dPoisLGG_AGHQ <- function(theta2, wi, yi, k, nodes, weights) {
    .Call(`_HZIP_dPoisLGG_AGHQ`, theta2, wi, yi, k, nodes, weights)
}

dBerLGG <- function(theta1, xi, yi, k) {
    .Call(`_HZIP_dBerLGG`, theta1, xi, yi, k)
}

dZIP <- function(theta1, theta2, xi, wi, yi, Qnodes, Qweights, log = FALSE) {
    .Call(`_HZIP_dZIP`, theta1, theta2, xi, wi, yi, Qnodes, Qweights, log)
}

lvero <- function(theta, xlist, wlist, ylist, Qnodes, Qweights) {
    .Call(`_HZIP_lvero`, theta, xlist, wlist, ylist, Qnodes, Qweights)
}

mlez_hat <- function(theta, xlist, wlist, ylist) {
    .Call(`_HZIP_mlez_hat`, theta, xlist, wlist, ylist)
}

